name: on-push

on:
  push:
    branches:
    - master
    tags:
    - '*'
  pull_request:
    branches:
    - master

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

defaults:
  run:
    shell: bash -l {0}

jobs:
  unit-tests:
    name: unit-tests
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.9", "3.12"]

    steps:
    - uses: actions/checkout@v4
    - name: Install Conda environment with Micromamba
      uses: mamba-org/setup-micromamba@v1
      with:
        environment-file: environment.yml
        environment-name: DEVELOP
        cache-environment: true
        create-args: >-
          python=${{ matrix.python-version }}
          ${{ matrix.optional-dependencies }}
    - name: Install package
      run: |
        python -m pip install --no-deps -e .
    - name: Run tests
      run: |
        make unit-tests COV_REPORT=xml
    - name: Upload coverage reports to Codecov
      uses: codecov/codecov-action@v3

  docs-build:
    needs: unit-tests
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Install Conda environment with Micromamba
      uses: mamba-org/setup-micromamba@v1
      with:
        environment-file: environment.yml
        environment-name: DEVELOP
        cache-environment: true
        create-args: >-
          python=3.11
    - name: Install package
      run: |
        python -m pip install --no-deps -e .
    - name: Build documentation
      run: |
        make docs-build
    - name: Deploy documentation
      if: github.ref == 'refs/heads/master'
      uses: peaceiris/actions-gh-pages@v4
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./docs/_build/html
